[versions]
# building
shadow = "8.1.1"

# utils
lombok = "1.18.34"
annotations = "24.1.0"
guice = "7.0.0"

# network
osgan = "1.2.17-SNAPSHOT"

#logging
log4j2 = "2.20.0"

# configuration
gson = "2.11.0"

# console
jline = "3.26.3"

[libraries]
# utils
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }

# network
osgan-netty = { group = "dev.httpmarco", name = "osgan-netty", version.ref = "osgan" }

# logging
log4j2 = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2" }
log4j2-simple = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j2" }


# configuration
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# console
jline = { group = "org.jline", name = "jline", version.ref = "jline" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }